export const CONSTRUCTION_TRADES = [
  "General Contractor",
  "Architectural Services",
  "Structural Engineering",
  "Mechanical Engineering (HVAC)",
  "Electrical Engineering",
  "Plumbing",
  "Civil Engineering",
  "Site Preparation & Excavation",
  "Concrete & Masonry",
  "Steel Erection & Fabrication",
  "Framing (Wood & Metal)",
  "Roofing & Waterproofing",
  "Exterior Finishes (Siding, Stucco)",
  "Glazing & Curtain Walls",
  "Drywall & Interior Finishes",
  "Painting & Coatings",
  "Flooring",
  "Tiling",
  "Millwork & Cabinetry",
  "Fire Protection Systems",
  "Security & Access Control",
  "Data & Communications Cabling",
  "Landscaping & Irrigation",
  "Paving & Roadwork",
  "Demolition",
  "Hazardous Material Abatement",
  "Surveying",
  "Geotechnical Engineering",
  "Building Automation & Controls",
  "Renewable Energy (Solar, Geothermal)",
  "Electrical Equipment",
  "Mechanical Equipment",
];
